# Generated by Django 5.2 on 2025-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='Тип техники')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('diagnostics', 'Диагностика'), ('repair', 'В ремонте'), ('waiting_parts', 'Ожидание запчастей'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предварительная стоимость')),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='Предполагаемая дата завершения')),
            ],
            options={
                'verbose_name': 'Заказ на ремонт',
                'verbose_name_plural': 'Заказы на ремонт',
            },
        ),
    ]
